spring.application.name=sri-web
server.port=${PORT:8087}
        
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

sri.api.base-url=${SRI_API_BASE_URL}
